services:
  - type: web
    name: bankaccount-api
    runtime: dotnet
    repo: https://github.com/TheRealCocky/bankaccount
    branch: main
    buildCommand: dotnet build -c Release
    startCommand: dotnet BankAccount.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: bankaccount-db
          property: connectionString

databases:
  - name: bankaccount-db
    databaseName: bankaccount
    user: bankuser


