services:
  - type: web
    name: bankaccount-api
    runtime: docker
    repo: https://github.com/TheRealCocky/bankaccount
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: bankaccount-db
          property: connectionString

databases:
  - name: bankaccount-db
    databaseName: bankaccount
    user: bankuser


